#!/usr/bin/env bash

git clone git@github.com:hmrc/address-lookup.git
git clone git@github.com:hmrc/agent-authorisation-api.git
git clone git@github.com:hmrc/agent-authorisation-test-support-api.git
git clone git@github.com:hmrc/api-example-microservice.git
git clone git@github.com:hmrc/api-notification-pull.git
git clone git@github.com:hmrc/api-platform-test-user.git
git clone git@github.com:hmrc/apprenticeship-levy.git
git clone git@github.com:hmrc/bank-account-reputation.git
git clone git@github.com:hmrc/breathing-space-if-dynamic-stub.git
git clone git@github.com:hmrc/breathing-space-if-proxy.git
git clone git@github.com:hmrc/business-details-api.git
git clone git@github.com:hmrc/business-rates-api.git
git clone git@github.com:hmrc/business-rates-test-support-api.git
git clone git@github.com:hmrc/check-eori-number-api.git
git clone git@github.com:hmrc/cis-deductions-api.git
git clone git@github.com:hmrc/common-transit-convention-traders.git
git clone git@github.com:hmrc/compliance-cases-api.git
git clone git@github.com:hmrc/compliance-documents-api.git
git clone git@github.com:hmrc/customer-profile.git
git clone git@github.com:hmrc/customs-declarations.git
git clone git@github.com:hmrc/customs-declarations-information.git
git clone git@github.com:hmrc/customs-financials-api.git
git clone git@github.com:hmrc/customs-inventory-linking-exports.git
git clone git@github.com:hmrc/customs-inventory-linking-imports.git
git clone git@github.com:hmrc/enrolment-store-proxy.git
git clone git@github.com:hmrc/epaye-api.git
git clone git@github.com:hmrc/get-nino-api.git
git clone git@github.com:hmrc/goods-movement-system-carrier-api.git
git clone git@github.com:hmrc/goods-movement-system-haulier-api.git
git clone git@github.com:hmrc/goods-movement-system-port-api.git
git clone git@github.com:hmrc/help-to-save-api.git
git clone git@github.com:hmrc/identity-verification.git
git clone git@github.com:hmrc/import-control-entry-declaration-intervention.git
git clone git@github.com:hmrc/import-control-entry-declaration-outcome.git
git clone git@github.com:hmrc/import-control-entry-declaration-store.git
git clone git@github.com:hmrc/individual-benefits.git
git clone git@github.com:hmrc/individual-calculations-api.git
git clone git@github.com:hmrc/individual-employment.git
git clone git@github.com:hmrc/individual-income.git
git clone git@github.com:hmrc/individual-income-des-stub.git
git clone git@github.com:hmrc/individual-losses-api.git
git clone git@github.com:hmrc/individual-tax.git
git clone git@github.com:hmrc/individuals-benefits-and-credits-api.git
git clone git@github.com:hmrc/individuals-business-eops-api.git
git clone git@github.com:hmrc/individuals-charges-api.git
git clone git@github.com:hmrc/individuals-details-api.git
git clone git@github.com:hmrc/individuals-disclosures-api.git
git clone git@github.com:hmrc/individuals-employments-api.git
git clone git@github.com:hmrc/individuals-expenses-api.git
git clone git@github.com:hmrc/individuals-if-api-stub.git
git clone git@github.com:hmrc/individuals-income-api.git
git clone git@github.com:hmrc/individuals-income-received-api.git
git clone git@github.com:hmrc/individuals-matching-api.git
git clone git@github.com:hmrc/individuals-reliefs-api.git
git clone git@github.com:hmrc/individuals-state-benefits-api.git
git clone git@github.com:hmrc/interest-restriction-return.git
git clone git@github.com:hmrc/iv-orchestration.git
git clone git@github.com:hmrc/lisa-api.git
git clone git@github.com:hmrc/marriage-allowance.git
git clone git@github.com:hmrc/marriage-allowance-des-stub.git
git clone git@github.com:hmrc/mobile-audit.git
git clone git@github.com:hmrc/mobile-help-to-save.git
git clone git@github.com:hmrc/mobile-messages.git
git clone git@github.com:hmrc/mobile-office-of-transit.git
git clone git@github.com:hmrc/mobile-paye.git
git clone git@github.com:hmrc/mobile-push-notifications-registration.git
git clone git@github.com:hmrc/mobile-rds-vehicle-private.git
git clone git@github.com:hmrc/mobile-rds-vehicle-public.git
git clone git@github.com:hmrc/mobile-startup.git
git clone git@github.com:hmrc/mobile-tax-credits-renewal.git
git clone git@github.com:hmrc/mobile-tax-credits-summary.git
git clone git@github.com:hmrc/mobile-user-contact.git
git clone git@github.com:hmrc/national-insurance.git
git clone git@github.com:hmrc/national-insurance-des-stub.git
git clone git@github.com:hmrc/national-insurance-record.git
git clone git@github.com:hmrc/native-apps-api-orchestration.git
git clone git@github.com:hmrc/oauth.git
git clone git@github.com:hmrc/obligations-api.git
git clone git@github.com:hmrc/openid-connect-userinfo.git
git clone git@github.com:hmrc/other-deductions-api.git
git clone git@github.com:hmrc/paye-des-stub.git
git clone git@github.com:hmrc/payments-bin-check.git
git clone git@github.com:hmrc/payments-processor.git
git clone git@github.com:hmrc/personal-income.git
git clone git@github.com:hmrc/property-business-api.git
git clone git@github.com:hmrc/push-pull-notifications-api.git
git clone git@github.com:hmrc/ras-api.git
git clone git@github.com:hmrc/real-time-income-information.git
git clone git@github.com:hmrc/secure-data-exchange-bulk-download.git
git clone git@github.com:hmrc/secure-data-exchange-notifications.git
git clone git@github.com:hmrc/self-assessment-accounts-api.git
git clone git@github.com:hmrc/self-assessment-api.git
git clone git@github.com:hmrc/self-assessment-biss-api.git
git clone git@github.com:hmrc/self-assessment-bsas-api.git
git clone git@github.com:hmrc/sso.git
git clone git@github.com:hmrc/sso-frontend.git
git clone git@github.com:hmrc/sso-session-api.git
git clone git@github.com:hmrc/sso-session-link-api.git
git clone git@github.com:hmrc/state-pension.git
git clone git@github.com:hmrc/state-pension-calculation.git
git clone git@github.com:hmrc/submission-tracker.git
git clone git@github.com:hmrc/telephony-identity-verification-api.git
git clone git@github.com:hmrc/telephony-identity-verification-test-api.git
git clone git@github.com:hmrc/transit-movement-api.git
git clone git@github.com:hmrc/txm-fph-validator-api.git
git clone git@github.com:hmrc/userid-recovery-api.git
git clone git@github.com:hmrc/vat-api.git
git clone git@github.com:hmrc/vat-registered-companies-api.git
git clone git@github.com:hmrc/voice-biometrics.git
